### ISSUE TITLE
Regression starting 3.5.0 - can't add roles

### ISSUE THREAD

**Issue by dhampik** [RolifyCommunity/rolify#310] opened 2015-01-11 21:52 UTC
First, I used rolify v 3.5.1
I added it to Gemfile
~~~
bundle install
rails g rolify Role
bin/rake db:migrate
bin/rails console
Loading development environment (Rails 4.2.0)
2.2.0 :001 > user = User.find(1)
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
 => #<User id: 1, username: "test", crypted_password: "xxx", created_at: "2015-01-11 09:11:09", updated_at: "2015-01-11 09:11:09", remember_me_token: "xxx", remember_me_token_expires_at: "2015-01-18 16:43:09"> 
2.2.0 :002 > user.roles
  Role Load (0.2ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = ?  [["user_id", 1]]
 => #<ActiveRecord::Associations::CollectionProxy []> 
2.2.0 :003 > user.add_role :admin
  Role Load (0.2ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = ? AND "roles"."resource_type" IS NULL AND "roles"."resource_id" IS NULL  ORDER BY "roles"."id" ASC LIMIT 1  [["name", "admin"]]
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
  HABTM_Roles Load (0.1ms)  SELECT "users_roles".* FROM "users_roles" WHERE "users_roles"."user_id" = ?  [["user_id", 1]]
 => #<Role id: nil, name: "admin", resource_id: nil, resource_type: nil, created_at: nil, updated_at: nil> 
2.2.0 :004 > user.roles
 => #<ActiveRecord::Associations::CollectionProxy []> 
# we have a problem here!
~~~

Then I reverted everything (including config and role model and user model), did the same with rolify v 3.4.1 and it worked well! Fix it please

**Comment by lesterchan** [comment] 2015-01-12 02:12
Yeap the same for me as well.
```
Mongoid::Errors::Validations:
Problem:
  Validation of User failed.
Summary:
  The following errors were found: Roles is invalid
Resolution:
  Try persisting the document with valid data or remove the validations.
from /Library/Ruby/Gems/2.0.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:78:in `fail_due_to_validation!'
```

**Comment by andradei** [comment] 2015-01-12 16:12
@dhampik Would you post your User model? (presumably the `user.rb` file)

**Comment by dhampik** [comment] 2015-01-12 19:17
Sure, it's simple
~~~ruby
# app/models/user.rb
class User < ActiveRecord::Base
  rolify
  authenticates_with_sorcery!
end
~~~

**Comment by aaronlerch** [comment] 2015-01-12 20:56
It looks like the regression was introduced with PR #303 -- specifically the situation where you do not have any models that are marked with `resourcify`, such that the newly added `Rolify.resource_types` is empty.

Or more specifically, the list of resources that call `resourcify` only gets populated as each one is included -- which in a lazy-loaded environment just plain doesn't work (to get a complete list). IMHO the PR should be re-evaluated and redesigned or reconsidered for inclusion.

In the meantime, removing the `resource_type` validation on `Role` is sufficient to work around the bug. I imagine any existing applications that haven't re-run a generator won't have this problem because the validation won't have been added unless they did it manually.

**Comment by josephbridgwaterrowe** [comment] 2015-01-13 23:09
I just added allow_nil => true to make it work for me.

```ruby
  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true
```

**Comment by andradei** [comment] 2015-01-14 09:31
Thank you for the suggestion @josephbridgwaterrowe. Version 3.5.1 fixes this regression. Closing.

**Comment by dhampik** [comment] 2015-01-14 09:37
But how does v 3.5.1 if it was already released on January 9, 2015 and this is the version where I found the regression?

**Comment by lesterchan** [comment] 2015-01-14 09:51
@andradei 3.5.1 has the same problem as well

**Comment by andradei** [comment] 2015-01-14 16:50
@lesterchan Checked it this morning and noticed the Rubygems are not up-to-date with the Github repo.

I found out I don't have current credentials to push new version notifications there. This will be fixed today and we will roll out a new version.

For the time being, please remove rolify with `gem uninstall rolify` and replace the rolify dependency in the _Gemfile_ to `gem 'rolify', git: 'https://github.com/RolifyCommunity/rolify.git', tag: 'v3.5.1'`

I'm reopening the Issue until Rubygems' system is noticfied of the recent changes.

Keep a look for updated version.

**Comment by andradei** [comment] 2015-01-14 17:21
New version (3.5.2) released. You can go back to using `gem 'rolify'` in your _Gemfile_.

**Closed by andradei** 2015-01-14 17:21 UTC
Labels: 3.x, High Priority, Regression

**Comment by tomascharad** [comment] 2016-08-09 21:56
I'm using rolify 5.1.0 with mongoid 6.0.0, and I receive the following in my user record after trying to ```add_role```

```bash
... @messages={:roles=>["is invalid"]}, @details={:roles=>[{:error=>:invalid}]}
```
