### ISSUE TITLE
Rolify doesn't work inside engines

### ISSUE THREAD

**Issue by ghost** [RolifyCommunity/rolify#238] opened 2014-03-27 00:32 UTC
I have devise setup inside of my engine, however, the Rolify generates do not work inside the engine.

rails g rolify Role User
error:  "uninitialized constant User"

So I then just created the necessary files without the generator.  I would then get an error on rake db:migrate stating "uninitialized constant Role".

So I put:  require 'rolify'
inside of my engine.rb file.

Still nothing.  What's wrong?

**Comment by Svashta** [comment] 2015-04-03 10:49
Is this still not merged?

**Comment by mido18** [comment] 2015-04-03 13:47
@svashta i think its still not merged

**Comment by wldcordeiro** [comment] 2015-04-03 17:06
@mido18 What PR is it? Can you link to it and is it working against the current codebase?

**Comment by samuelralak** [comment] 2015-09-25 09:09
I am the same problem here. @mido18 what is causing this problem and what was the fix?

**Comment by wldcordeiro** [comment] 2015-09-25 18:08
@mido18  there is no open or closed PR from you here, could you try creating one against the current repo head?

**Comment by mido18** [comment] 2015-09-25 18:15
@wldcordeiro Sorry what is PR ? also i don't know if it's working on the current codebase
@samuelralak The fix is in this link
https://github.com/mido18/rolify/commit/c7b4bc3d94140bf3b5d1cf92c945c1530026d872

**Comment by wldcordeiro** [comment] 2015-09-25 18:30
A PR is a pull request, your fix is over a hundred commits behind the Rolify upstream. I could take a look and see if it works with our current code base but if you could pull down changes from upstream and create a pull request it'd help a lot.

**Comment by mido18** [comment] 2015-09-25 19:17
@wldcordeiro okay i will try to do it :)

**Comment by wldcordeiro** [comment] 2015-09-25 20:38
Hmm it actually looks like I've already integrated your changes into the project at some point but the issue is still present. 
https://github.com/RolifyCommunity/rolify/blob/master/lib/generators/active_record/rolify_generator.rb#L16

**Comment by mido18** [comment] 2015-09-25 21:01
@wldcordeiro i think you must pass "engine" and "devise" as args when you use 
"rails g rolify Role User" so the generator will be something like this
"rails g rolify Role User engine devise"

**Comment by mido18** [comment] 2015-09-25 21:05
@wldcordeiro 
I added this to gem documentation on my fork 

1. Generate Role Model

First, create your Role model and migration file using this generator:

rails g rolify Role User
if you use rolify inside eninge your generator:

rails g rolify Role User engine
if your user model have devise dependency then your generator:

rails g rolify Role User engine devise

**Comment by wldcordeiro** [comment] 2015-09-25 21:10
Ah, I see. That needs to be added to the docs somewhere. :smile: I'll figure that out and add that.

**Comment by wldcordeiro** [comment] 2015-09-25 21:10
@samuelralak the solution has been posted if you're on the newest version of Rolify.

**Comment by mido18** [comment] 2015-09-25 21:27
@wldcordeiro Cool :+1:

**Comment by EppO** [comment] 2015-10-15 18:52
@wldcordeiro: can you please point out the commit or the wiki page regarding that issue in order to close it?

**Comment by mhoad** [comment] 2018-03-27 06:31
Just wanted to let people know that `rails g rolify Role User engine devise` no longer appears to work. The correct method for ensuring Rolify works within a mounted engine is 

1. Add rolify to your `gemspec` with
`s.add_dependency 'rolify', '~> 5.2'`
2. Run the generator as such
`bin/rails generate rolify Role YourEngineName::User`
3. Add the following to your `user.rb` file
`rolify role_cname: 'YourEngineName::Role'`
4. Add the following to the class you want to resourcify
`resourcify role_cname: 'YourEngineName::Role'`
5. Add the following to `lib/yourenginename.rb`
`require 'rolify'`

**Comment by EppO** [comment] 2019-02-28 16:26
Added Engine docs in [wiki](https://github.com/RolifyCommunity/rolify/wiki/FAQ#install-rolify-in-a-rails-engine), thanks!

**Closed by EppO** 2019-02-28 16:26 UTC
Labels: feature requests
