### ISSUE TITLE
rolify.rb:30: warning: Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by yshmarov** [RolifyCommunity/rolify#542] opened 2020-05-21 12:10 UTC
When running commands in the console I get this
`/home/ubuntu/.rvm/gems/ruby-2.7.1/gems/rolify-5.2.0/lib/rolify.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

Any idea what to do about it?

Rails 6.0.3
Ruby 2.7.1

**Comment by alaarab** [comment] 2020-05-27 09:31
I am also getting this issue.

**Comment by ThomasConnolly** [comment] 2020-05-29 11:41
Me, too

**Comment by alaarab** [comment] 2020-05-29 21:59
https://github.com/RolifyCommunity/rolify/pull/541 This pull request seems to resolve this issue.

**Comment by thomas-mcdonald** [comment] 2020-06-01 10:55
Closing as duplicate of #528

**Closed by thomas-mcdonald** 2020-06-01 10:55 UTC
